In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart.csv

In [ ]:
df = pd.read_csv("heart.csv")
df.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
X = df.drop("target",1)
Y = df["target"]

<ipython-input-4-db297d0c0a06>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df.drop("target",1)

In [ ]:
df

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
corr=df.corr()
cor_target = abs(corr["target"])
relevant_features = cor_target[cor_target>=0.20]
relevant_features

age        0.225439
gender     0.280937
cp         0.433798
thalach    0.421741
exang      0.436757
oldpeak    0.430696
slope      0.345877
ca         0.391724
thal       0.344029
target     1.000000
Name: target, dtype: float64

In [ ]:
X_new = df[['age','gender','cp','thalach','exang','oldpeak','slope','ca','thal','target']]
X_new

     age  gender  cp  thalach  exang  oldpeak  slope  ca  thal  target
0     63       1   3      150      0      2.3      0   0     1       1
1     37       1   2      187      0      3.5      0   0     2       1
2     41       0   1      172      0      1.4      2   0     2       1
3     56       1   1      178      0      0.8      2   0     2       1
4     57       0   0      163      1      0.6      2   0     2       1
..   ...     ...  ..      ...    ...      ...    ...  ..   ...     ...
298   57       0   0      123      1      0.2      1   0     3       0
299   45       1   3      132      0      1.2      1   0     3       0
300   68       1   0      141      0      3.4      1   2     3       0
301   57       1   0      115      1      1.2      1   1     3       0
302   57       0   1      174      0      0.0      1   1     2       0

[303 rows x 10 columns]

#23 feb training dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X_new, Y, test_size=0.3)
print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

Train set: (212, 10) (212,)
Test set: (91, 10) (91,)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
k = 6
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=6)

In [ ]:

yhat = neigh.predict(X_test)

In [ ]:

from sklearn import metrics

In [ ]:
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.7688679245283019
Test set Accuracy:  0.7362637362637363